steps:

  #CREATE AN IMAGE FROM DOCKERFILE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/company-hub-286820/fullcycle:latest', '-t', 'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA', '.' ]

  #CREATE AN CONTAINER FROM FULLCYCLE IMAGE
- name: 'docker'
  args: ['run', '-d','--name', 'companyHUBa', '-t', 'gcr.io/company-hub-286820/fullcycle:latest'] 

- name: 'docker'
  args: ['ps']

 

timeout: 1200s  

 
   
