steps:

  #CREATE AN IMAGE FROM DOCKERFILE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',          
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:latest', 
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA', '.' ]
  env:
    - 'DB_HOST=ec2-34-200-15-192.compute-1.amazonaws.com'

  #CREATE AN CONTAINER FROM FULLCYCLE IMAGE
- name: 'docker'
  args: ['run', '-d','--name', 'companyHUB', '-t', 'gcr.io/company-hub-286820/fullcycle:latest'] 
  env:
    - 'DB_HOST=ec2-34-200-15-192.compute-1.amazonaws.com'
 
- name: 'docker'
  args: ['exec', 'companyHUB', 'npm', 'run', 'start']
  env:
    - 'DB_HOST=ec2-34-200-15-192.compute-1.amazonaws.com'
 

timeout: 1200s  

 
   
