steps:

  #CREATE AN IMAGE FROM DOCKERFILE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',  
         '--build-arg',
         'REDIS_PASS=$$DB_HOST',               
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:latest', 
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA', '.' ]
  secretEnv: ['DB_HOST']       
   

  #CREATE AN CONTAINER FROM FULLCYCLE IMAGE
- name: 'docker'
  args: ['run', '-d','--name', 'companyHUB', '-t', 'gcr.io/company-hub-286820/fullcycle:latest'] 
  
 
- name: 'docker'
  args: ['exec', 'companyHUB', 'npm', 'run', 'start']

secrets:
- kmsKeyName: projects/vmi-integration/locations/global/keyRings/vmi-integration-secrets/cryptoKeys/vertigo-js-node-api
  secretEnv:
    DB_HOST: ec2-34-200-15-192.compute-1.amazonaws.com
