steps:

 
- name: gcr.io/cloud-builders/wget
  entrypoint: bash
  args:
    - -c
    - wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy

 
- name: gcr.io/cloudsql-docker/gce-proxy:1.17
  entrypoint: bash
  args:
    - -c
    - /cloud_sql_proxy -instances=company-hub-286820:us-central1:company=tcp:5432              
  timeout: '1200s'


  #CREATE AN IMAGE FROM DOCKERFILE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',          
         '--build-arg',
         'MAIL_PASS=${_MAIL_PASS}',
         '--build-arg',
         'MAIL_USER=${_MAIL_USER}',
         '--build-arg',
         'MAIL_SERVICE=${_MAIL_SERVICE}',            
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:latest', 
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA', '.' ]   

- name: 'docker'
  args: ['run', '-d','--name', 'companyHUB', '-t', 'gcr.io/company-hub-286820/fullcycle:latest']      
 
- name: 'docker'
  args: ['push', 'gcr.io/company-hub-286820/fullcycle:latest']

- name: 'docker'
  args: ['push', 'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA'] 

- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set',
    'image',
    'deployment',
    'companyhub',
    'companyhub=gcr.io/company-hub-286820/fullcycle:$SHORT_SHA'
  ]    
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=chbackend'
    
  

 
