steps:


  #CREATE AN IMAGE FROM DOCKERFILE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',  
         '--build-arg',
         'DB_HOST=${_DB_HOST}', 
         '--build-arg',
         'DB_USER=${_DB_USER}',
         '--build-arg',
         'DB_PASSWORD=${_DB_PASSWORD}',
         '--build-arg',
         'DB_NAME=${_DB_NAME}', 
         '--build-arg',
         'MAIL_PASS=${_MAIL_PASS}',
         '--build-arg',
         'MAIL_USER=${_MAIL_USER}',
         '--build-arg',
         'MAIL_SERVICE=${_MAIL_SERVICE}',            
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:latest', 
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA', '.' ]   

- id: proxy-install
  name: alpine:3.10
  entrypoint: sh
  args:
    - -c
    - 'wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy &&  chmod +x cloud_sql_proxy'
  waitFor: ['-'] 

- id: testing
  name: python:3.7
  timeout: 1000s
  entrypoint: sh
  args:
    - -c
    - '( ./cloud_sql_proxy -instances=company-hub-286820:us-central1:company=tcp:5432 & sleep 2)'
  waitFor: ['proxy-install']   
 
- name: 'docker'
  args: ['run', '-d','--name', 'companyHUB', '-t', 'gcr.io/company-hub-286820/fullcycle:latest']  
  waitFor: ['testing']  


- name: 'docker'
  args: ['ps', '-a']

- name: 'docker'
  args: ['exec', 'companyHUB', 'npm', 'run', 'migration:run']  
  
- name: 'docker'
  args: ['push', 'gcr.io/company-hub-286820/fullcycle:latest']

- name: 'docker'
  args: ['push', 'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA'] 

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 
        'deploy', 
        'companyzada', 
        '--image', 
        'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed']    
    
  

 
