steps:

  #CREATE AN IMAGE FROM DOCKERFILE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',          
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:latest', 
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA', '.' ]
  env:    
    - '_OI=FULHODUMAPUTA'
 

  #CREATE AN CONTAINER FROM FULLCYCLE IMAGE
- name: 'docker'
  args: ['run', '-d','--name', 'companyHUB', '-t', 'gcr.io/company-hub-286820/fullcycle:latest'] 
  env:
    - '_OI=FULHODUMAPUTA'
  

- name: 'docker'
  args: ['exec', 'companyHUB', 'npm', 'run', 'test']
  env:
    - '_OI=FULHODUMAPUTA'
    

 

timeout: 1200s  

 
   
