steps:
   
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',  
         '--build-arg',
         'DB_HOST=${_DB_HOST}', 
         '--build-arg',
         'DB_USER=${_DB_USER}',
         '--build-arg',
         'DB_PASSWORD=${_DB_PASSWORD}',
         '--build-arg',
         'DB_NAME=${_DB_NAME}', 
         '--build-arg',
         'MAIL_PASS=${_MAIL_PASS}',
         '--build-arg',
         'MAIL_USER=${_MAIL_USER}',
         '--build-arg',
         'MAIL_SERVICE=${_MAIL_SERVICE}',            
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:latest', 
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA', '-f',
         'Dockerfile.dev', '.' ]   

- name: 'docker'
  args: ['run', '-d','--name', 'companyHUB', '-t', 'gcr.io/company-hub-286820/fullcycle:latest']  

- name: 'docker'
  args: ['exec', 'companyHUB', 'yarn', 'lint']

- name: 'docker'
  args: ['exec', 'companyHUB', 'yarn', 'test']
 
- name: 'docker'
  args: ['push', 'gcr.io/company-hub-286820/fullcycle:latest']

- name: 'docker'
  args: ['push', 'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA'] 

- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set',
    'image',
    'deployment',
    'companyhub',
    'companyhub=gcr.io/company-hub-286820/fullcycle:$SHORT_SHA'
  ]    
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=chbackend'
    
  

 
