steps:

  #CREATE AN IMAGE FROM DOCKERFILE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 
          '--build-arg',
         'OI=DWDWDFESD', 
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:latest', 
         '-t', 
         'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA', '.' ]
  env:    
    - 'OI=FULHODUMAPUTA'

  #CREATE AN CONTAINER FROM FULLCYCLE IMAGE
- name: 'docker'
  args: ['run', '-d','--name', 'companyHUB', '-t', 'gcr.io/company-hub-286820/fullcycle:latest'] 
  env:
    - 'OI=FULHODUMAPUTA'

- name: 'docker'
  args: ['exec', 'companyHUB', 'npm', 'run', 'test']
  env:
    - 'OI=FULHODUMAPUTA'

 

timeout: 1200s  

 
   
