steps:

  #CREATE AN IMAGE FROM DOCKERFILE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/company-hub-286820/fullcycle:latest', '-t', 'gcr.io/company-hub-286820/fullcycle:$SHORT_SHA', '.' ]
  env:
    - 'DB_HOST=ec2-34-200-15-192.compute-1.amazonaws.com'
    - 'DB_USER=ggcuzfmgehrtlj'
    - 'DB_PASSWORD=9ab5ee3ed7d5902f8cf8422573bb1937c35292478437ef8bdaf17a57827cdd5a'
    - 'DB_NAME=dd5igj8hv5eb0a'

  #CREATE AN CONTAINER FROM FULLCYCLE IMAGE
- name: 'docker'
  args: ['run', '-d','--name', 'companyHUB', '-t', 'gcr.io/company-hub-286820/fullcycle:latest'] 
  env:
    - 'DB_HOST=ec2-34-200-15-192.compute-1.amazonaws.com'
    - 'DB_USER=ggcuzfmgehrtlj'
    - 'DB_PASSWORD=9ab5ee3ed7d5902f8cf8422573bb1937c35292478437ef8bdaf17a57827cdd5a'
    - 'DB_NAME=dd5igj8hv5eb0a'

- name: 'docker'
  args: ['exec', 'companyHUB', 'npm', 'run', 'test']
  env:
    - 'DB_HOST=ec2-34-200-15-192.compute-1.amazonaws.com'
    - 'DB_USER=ggcuzfmgehrtlj'
    - 'DB_PASSWORD=9ab5ee3ed7d5902f8cf8422573bb1937c35292478437ef8bdaf17a57827cdd5a'
    - 'DB_NAME=dd5igj8hv5eb0a' 

 

timeout: 1200s  

 
   
