version: "3"
services: 
  app:
    container_name: companyHUB
    build: .
    command: yarn start:dev
    ports:
      - "3333:3333"
    volumes:      
      - ./:/usr/src/app
    env_files:
      - .env  
    
 
      
     
              