version: "3"

services: 
  app:
    container_name: companyHUB
    build: .
    command: yarn start:prod
    ports:
      - "3333:3333"
    volumes:      
      - ./:/usr/src/app
      - /usr/src/app/node_modules
 
      
     
              