apiVersion: v1
kind: Service
metadata:
    name: companyhub-service
    labels:
      app: companyhub
spec:
  type: LoadBalancer
  ports:
      - protocol: TCP
        name: http-svc
        port: 80
        targetPort: 8080
  selector:
      app: companyhub 